### PR TITLE
Adding convert function: Planar simplex to projection maps coordinates

### PR DESCRIPTION
**Pull request by luizkeng**
I added a function to convert planar simplex (regular x, y) to projection maps coordinates (ternary x, y, z). This was useful for me to take the (x,y) mouse position and convert to corresponding ternary coordinates to perform zoom or re-scale by mouse events. 

See #134

### CODE REVIEW

**Comment by marcharper** [comment]
Thanks! Can you add a test [here](https://github.com/marcharper/python-ternary/blob/master/tests/test_helpers.py) that checks that this function on some explicit values?

**Comment by luizkeng** [comment]
Sure. I added the test that you require. Please, check if it is ok.

**Comment by marcharper** [comment]
That's fine. FYI you can just push more commits to the same branch and they'll show up in the pull request. (That's a Github behavior rather than a git behavior.)

**Comment by luizkeng** [comment]
That's ok. Thanks for this information. I didn't know this Github behavior, but I'll make it in future PRs.

**Pull request merged**
