### PR TITLE
Added left,right,top_corner_label methods 

### PR DESCRIPTION
**Pull request by ZGainsforth**
Added left,right,top_corner_label methods to allow labeling of ternary plot at each corner instead of along each axis.  Folks in geology tend to draw plots this way.  Future work might make the positioning of the labels within the canvas.

### CODE REVIEW

**Comment by marcharper** [comment]
Thanks for the contribution! I'll run through a few examples and tests today, looks good so far.

**Comment by marcharper** [comment]
The relative positions look good, but in some of my examples the corner labels are outside the standard plotting boundary, e.g. the top label is above the plot title. I suspect this related to the scale parameter, so I think we might need to resize the plotting area appropriately to make sure that the corner labels stay in frame. Do you have an example plot? If not I'll see if I can compute resizing parameters for some of the example plots.

I'm also going to add a convenience function to set all the labels simultaneously, something like
```
def corner_labels(self, left_label, right_label, top_label):
    ...
```

I should probably have done this for the axes labels as well. So I'm going to open a new PR on a branch "corner_labels" for your commit and make the additional changes I just described there before merging into master.

**Comment by ZGainsforth** [comment]
Hi Marc,

Glad to help!  I love how there is a library for everything.  :-)

Yes, the labels went outside the active area.  I agree it would be better to enlarge the area so they fit inside, but I wasn’t familiar enough with your class structure to do that cleanly.  The plot looks like this:



I’ll send the source code as a zip in a second e-mail in case you have filters.

The convenience functions are a good idea.  

Zack

**Comment by ZGainsforth** [comment]
Second e-mail with zip.

**Comment by marcharper** [comment]
Great I'll work on this as soon as I get a chance, will probably be a few days.

**Comment by ZGainsforth** [comment]
Terrific!  Glad to be able to help.

Zack

**Comment by KyomaHooin** [comment]
Break _redraw_labels():

` def right_corner_label(..):`
......
`self._labels["left"] = (label, position, rotation, kwargs)`

"left" overwrite regular label dictionary key.

**Comment by marcharper** [comment]
Yes this PR would break the axis labels. We would need to add a new dictionary for the corner labels. There are also some spacing issues if the corner labels are large (described above). I'm happy to merge a PR that fixes these issues.

**Comment by Gotzias** [comment]
Hi Mark, 
i used the python ternary library in a recent publication, 
i want to include this work in the specified section Citations and Recent Usage in Publications in the readme.md, 
Enhanced CO2 selectivity within the cavity of gmelinite frameworks, by Anastasios Gotzias,  Michael Kainourgiakis and Athanassios Stubos (2018).
 https://doi.org/10.1007/s10450-018-9945-2

**Comment by marcharper** [comment]
Thanks for letting me know about the paper, I'll add it to the others. The preferred citation string is:

```Marc Harper et al.. (2015). python-ternary: Ternary Plots in Python. Zenodo. 10.5281/zenodo.34938```

**Comment by marcharper** [comment]
Hey, I merged this commit in #83. Thanks for the contribution!

**Comment by ZGainsforth** [comment]
Great to hear!  My pleasure!

When it's up on pypi I'll go grab it and use the new version.

Zack

**Comment by marcharper** [comment]
It should be there already, and in conda-forge.

**Comment by carlosgmartin** [comment]
> Future work might make the positioning of the labels within the canvas.

> The relative positions look good, but in some of my examples the corner labels are outside the standard plotting boundary, e.g. the top label is above the plot title.

> Yes, the labels went outside the active area. I agree it would be better to enlarge the area so they fit inside, but I wasn’t familiar enough with your class structure to do that cleanly.

Looks like this relates to #203.

**Pull request closed without merging**
