### PR TITLE
Add normalize_tick parameters

### PR DESCRIPTION
**Pull request by hitliaomq**
Add normalize_tick to contral normalize the tick or not
Add the `build`,  `dist`, `*.egg-info` folder in the .gitignore
Change the version from `1.0.6` to `1.0.7` to adapt the release version

### CODE REVIEW

**Comment by marcharper** [comment]
Hi, thanks for catching the version number issue. However I'm not sure I like the idea of `normalize_tick` -- one can already achieve this by either setting custom ticks or normalizing the data to `scale=1`. Moreover I'm not sure this will interact well with the option to set a tick format. If you'd like to discuss please open an issue.

**Comment by hitliaomq** [comment]
@marcharper 
Thank you for reply. I cancelled the `normalize_tick`.
Instead, I made the following modification:
1. change the version from `1.0.6` to `1.0.7` in both `setup.py` and `__init__.py`
2. rotate the ticks
3. instead using the coordinate before transformed to ternary system, I used the coordinate after transformed. And I add a unit coefficient, which is related with the `fontsize`, to contral the `offset`.
For details, please ref. the code

**Comment by marcharper** [comment]
Hi, if you open a PR with just the version changes, I'll merge that. The other proposed changes will have to be tested and could alter people's existing outcomes (e.g. changing how the offsets work).

**Comment by hitliaomq** [comment]
When change the font size of ticks (larger than 10, e.g. 20), the original result is really a disaster. Of course, it can be improved by enlarge `offset`, which means each font size has an appropriate offset, then this two parameters are not independent.

In our current scheme, we release this dependence, and the user can adjust this two parameters indpendently. I hope you can adopt it. If you don't like this, I will close this PR and I will keep this feature in my fork, as a result, I won't change back and create a PR only for the version change. Of course, you can change the version as you like.

The followings are some tests.

## For changing fontsize
FONTSIZE=20
Before
image
After:
image

Of course, you can easily change the space by adjusting `k_tick`(line 276 in `lines.py`). I did several tests, maybe `k_tick = 1 + 0.002/offset*scale * fontsize` (I have made a new commit) will be a better choice, it will give the following result.
image


## For changing offset

When only change the offset, current scheme is not worse than previous.

Default Setting(font=10, offset=0.01)
Before:
image
`k_tick = 1 + 0.002/offset*scale * fontsize`
image

OFFSET=0.02
Before:
image
`k_tick = 1 + 0.002/offset*scale * fontsize`
image

OFFSET=0.03
Before:
image
`k_tick = 1 + 0.002/offset*scale * fontsize`
image

## Test code
```
import ternary
import math
import matplotlib.pyplot as plt
def shannon_entropy(p):
   """Computes the Shannon Entropy at a distribution in the simplex."""
   s = 0.
   for i in range(len(p)):
       try:
           s += p[i] * math.log(p[i])
       except ValueError:
           continue
   return -1.*s

scale = 20
multiple = scale/5.
fontsize = 30
offset = 0.01

figure, tax = ternary.figure(scale=scale)
tax.heatmapf(shannon_entropy, boundary=True, style="triangular")
tax.boundary(linewidth=2.0)
tax.set_title("Shannon Entropy Heatmap")
tax.ticks(axis='lbr', linewidth=1, multiple=multiple, fontsize=fontsize, clockwise=False, offset=offset)
tax.clear_matplotlib_ticks()
plt.axis('off')

tax.show()
```

**Comment by marcharper** [comment]
Hi, thanks for the effort here, however it's more complicated than just picking a specific offset correction value/scheme. I've found that rendering can differ between clients and based on other factors (the font weight, the font itself, use of LaTeX symbols, etc.). So while this looks better on your machine with these specific choices, there's no guarantee it will work better in other scenarios, or handle other fonts or dimensions better.

It's also your preference to have the ticks rotated. Others will not necessarily share that preference, and whether the ticks are rotated, bolded, etc. or not will determine if the spacing works well.

Currently manually tuning the offset works, even if sometimes a bit tedious. Your plots do show that the 0.02 seems to look better than 0.01 -- that's a small change with probably overall positive consequence that doesn't require a lot of testing. So if you want to open a PR for that, and all the examples in the example notebook look fine, then I'll merge that. And I'll still merge a PR fixing the version numbers (which I'll do regardless).

Better solutions to these rendering issues would be to integrate ternary more deeply into matplotlib, using its native transformations, for example, or interact more closely with mpl to see the actual boundaries of the rendered text elements and respond appropriately. These are both significant rewrite efforts.

**Comment by hitliaomq** [comment]
Thank you for your reply and thank you for providing this good package.

Yes, I can understand that the proper ticks suitable for everyone is a complex work and not easy. As for me, the modification I did is enough and I will keep that in my fork. So, I won't change it back to open a pull request for the version or the default settings for offset. Of course, you can do this without any warries.

Thank you again.

Bests

**Pull request closed without merging**
