### PR TITLE
Add Inkscape SVG for heatmap grids and exported PNGs.

### PR DESCRIPTION
**Pull request by chebee7i**
This PR add a source Inkscape SVG that was used to generate PNGs for the heatmap grid structure used in the `'triangular'` and `'dual-triangular'` styles.

I'm kept the labeling from the other examples, but it might be nice to eventually allow this to be customizable and more uniform. I'll open another ticket for that.

### CODE REVIEW

**Comment by chebee7i** [comment]
Should I include the Python file and PNG for the 3x1 matplotlib plot on this branch as well?

**Comment by chebee7i** [comment]
I should've attached this to #11. Oh well.

**Comment by marcharper** [comment]
Please add the python file for the other plot as well and I'll merge this in.

**Comment by chebee7i** [comment]
I added both gray-scale and [cubehelix](http://www.ifweassume.com/2013/05/cubehelix-or-how-i-learned-to-love.html) versions of the matplotlib plots. Personally, it was easier for me to read the colored version as my eye immediately jumped to the appropriate section of the colorbar, but I realize this varies with the individual.

Feel free to rename, modify, and reorganize as you see fit.

**Comment by marcharper** [comment]
Thanks!

**Pull request merged**
