### PR TITLE
Change tickslabel fontsize

### PR DESCRIPTION
**Pull request by jl-bernal**
Just added a new argument in ticks (inside lines.py) to allow to change the fontsize of the tickslabel. 

ticks(.....,fsize=[fontsize],.....)

### CODE REVIEW

**Comment by marcharper** [comment]
Hi @jl-bernal thanks for the PR! It looks like something unusual going on with `lines.py` -- I think you've added it to the root directory rather than modified the file in place.

I can fix it, but if you want to get credit for the contribution on github it would be better if you give it a try. Let me know either way.

**Comment by jl-bernal** [comment]
Hi marc! Thank you for your mail, it's my first contribution to github, so
let me try it again please! I'll do it next week.

Cheers,
Jose

**Comment by jl-bernal** [comment]
Hi marc. I think now it's done. Let me know if I have to do something else.

**Comment by marcharper** [comment]
Thanks @jl-bernal. Can you run the following commands:
```
git rebase -i origin master
```
Then change "pick" to "squash" for the last two commits. After that run:

```
git push -f master
```

This will combine your commits so that the extra file was never added. I think we'll be good after that.

**Pull request merged**
